Allow running codacy from python using the `-m` flag
codacy/python-codacy-coverage pull request #40
Opened 2018-03-22 22:48 UTC by althonos

Hi there,

I just added a `__main__.py` file to allow running the program from Python directly instead of using an entry point (`python -m codacy`). The main perk is that it is not needed for `python-codacy-coverage` to be in `$PATH` anymore to be able to report coverage, but only for `codacy` to be in `$PYTHONPATH`. This makes it easier for some CI environments.

I also added a `prog` parameter to `runner.run` so that the program name can be changed: this way, instead of having `python -m codacy -h` display this:
```
usage: __main__.py [-h] [-r REPORT] [-c COMMIT] [-t TOKEN] [-d DIRECTORY] [-v]
```
it show this:
```
usage: codacy [-h] [-r REPORT] [-c COMMIT] [-t TOKEN] [-d DIRECTORY] [-v]
```
while `python-codacy-coverage -h` will show:
```
usage: python-codacy-coverage [-h] [-r REPORT] [-c COMMIT] [-t TOKEN] [-d DIRECTORY] [-v]
```

2018-03-23 17:58 UTC, rtfpessoa requested changes

2018-03-23 17:58 UTC, rtfpessoa commented on src/codacy/__main__.py
> +#/usr/bin/env python
Seems like you missed a bang here.
Can you change to `#!/usr/bin/env python`

2018-03-24 14:00 UTC, althonos commented
@rtfpessoa: Fixed, thanks.

2018-03-24 15:15 UTC, rtfpessoa approved these changes

2018-03-24 15:15 UTC, merged

2018-03-25 17:18 UTC, rtfpessoa commented
@althonos released as version 1.3.11